In [46]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.optimizers import Adam

In [47]:
data1 = pd.read_csv("Dataset/Train/Voltage_L1_DataSet1.csv")
out1 = pd.read_csv("Dataset/Train/OutputFor_DataSet1.csv")
data2 = pd.read_csv("Dataset/Test/Voltage_L1_DataSet2.csv")
out2 = pd.read_csv("Dataset/Test/OutputFor_DataSet2.csv")

In [48]:
print("data1",data1.shape)
print("out1",out1.shape)
print("data2",data2.shape)
print("out2",out2.shape)

data1 (11899, 128)
out1 (5999, 1)
data2 (5999, 128)
out2 (5999, 1)


In [49]:
data1.dropna(axis=0,inplace=True)

In [5]:
data1.shape

(5999, 128)

In [50]:
header =[]
for i in range(1,data1.shape[1]+1):
    header.append("Col"+str(i))

In [51]:
data1.columns = header
data2.columns = header

In [8]:
data1.head()

Col1         Col2         Col3         Col4         Col5  \
0  -797.962914 -1320.199586 -1828.741445 -2319.935857 -2789.218649   
1  4387.885674  4567.747164  4693.741356  4776.824895  4824.300958   
2 -4050.074299 -4340.408587 -4576.875995 -4769.518913 -4918.338175   
3  3458.450134  3686.700705  4000.773209  4392.451258  4834.343975   
4  -910.262100  -312.245917   298.552078   896.568469  1462.629392   

          Col6         Col7         Col8         Col9        Col10  ...  \
0 -3231.111864 -3641.962908 -4018.119193 -4355.929647 -4650.829055  ...   
1  4850.777519  4862.646175  4867.211521  4866.298624  4858.081691  ...   
2 -5025.159834 -5100.026323 -5141.111052 -5153.892968 -5137.458861  ...   
3  5269.845213  5636.871457  5876.078192  5950.944421  5841.384319  ...   
4  1978.474763  2439.540162  2847.652177  3212.852886  3547.924521  ...   

        Col119       Col120       Col121       Col122       Col123  \
0  4008.077109  3632.834002  3221.982426  2780.090228  2311.720161   
1  -850.916937  -165.252287   524.062959  1199.684611  1842.437384   
2  1161.338395   563.322919   -47.475988  -656.447463 -1252.637741   
3 -1450.758930  -722.183210    67.562203   850.005032  1561.232918   
4 -4805.126485 -4506.574476 -4196.154858 -3881.168803 -3560.705563   

        Col124       Col125       Col126       Col127       Col128  
0  1821.438861  1311.983509   790.659456   262.031836  -269.335205  
1  2437.714882  2972.733259  3437.450839  3828.215741  4143.201102  
2 -1825.089177 -2364.673580 -2861.346591 -3309.630078 -3706.785897  
3  2152.858410  2601.141643  2912.474970  3123.378574  3286.805684  
4 -3225.633496 -2860.433401 -2452.321914 -1991.255895 -1474.497200  

[5 rows x 128 columns]

In [9]:
data2.head()

Col1         Col2         Col3         Col4         Col5  \
0 -4918.927835 -4668.999112 -4375.127119 -4034.564431 -3659.213495   
1  2920.413836  2376.612648  1773.304349  1123.306756   444.013104   
2 -2808.723170 -2303.372710 -1758.656432 -1180.066319  -579.504820   
3  2871.892861  2532.245964  2055.275298  1435.488878   704.927781   
4  5534.138053  5395.898976  5186.251418  4924.421624  4631.464792   

          Col6         Col7         Col8         Col9        Col10  ...  \
0 -3247.243211 -2804.145676 -2333.584172 -1841.965323 -1332.037736  ...   
1  -248.097664  -933.799415 -1594.783666 -2213.654301 -2776.681104  ...   
2    32.957795   643.590017  1241.404644  1815.417600  2356.471851  ...   
3   -86.971408  -871.546088 -1584.713275 -2177.034698 -2625.625239  ...   
4  4323.859863  4009.847091  3692.171624  3363.511349  3012.878248  ...   

        Col119       Col120       Col121       Col122       Col123  \
0 -4663.506099 -4918.012016 -5121.251501 -5275.969344 -5381.249941   
1  4871.323226  4852.098262  4814.562485  4748.647181  4645.197563   
2 -5151.462319 -5106.602976 -5027.871511 -4914.350757 -4759.632168   
3  5858.221546  5590.898767  5202.730284  4759.633062  4322.945050   
4  3558.510431  3879.847783  4193.860201  4506.042306  4808.154800   

        Col124       Col125       Col126       Col127       Col128  
0 -5433.432863 -5434.348878 -5382.165656 -5278.715575 -5123.997634  
1  4492.310731  4274.423564  3991.537412  3633.580485  3201.469277  
2 -4565.548254 -4319.281944 -4020.831887 -3671.114971 -3265.552744  
3  3943.932165  3647.312850  3432.172965  3265.553468  3098.018896  
4  5085.548312  5318.082271  5487.448225  5576.250464  5574.419599  

[5 rows x 128 columns]

In [52]:
data = data1.append(data2, ignore_index = True)
data.head()

Col1         Col2         Col3         Col4         Col5  \
0  -797.962914 -1320.199586 -1828.741445 -2319.935857 -2789.218649   
1  4387.885674  4567.747164  4693.741356  4776.824895  4824.300958   
2 -4050.074299 -4340.408587 -4576.875995 -4769.518913 -4918.338175   
3  3458.450134  3686.700705  4000.773209  4392.451258  4834.343975   
4  -910.262100  -312.245917   298.552078   896.568469  1462.629392   

          Col6         Col7         Col8         Col9        Col10  ...  \
0 -3231.111864 -3641.962908 -4018.119193 -4355.929647 -4650.829055  ...   
1  4850.777519  4862.646175  4867.211521  4866.298624  4858.081691  ...   
2 -5025.159834 -5100.026323 -5141.111052 -5153.892968 -5137.458861  ...   
3  5269.845213  5636.871457  5876.078192  5950.944421  5841.384319  ...   
4  1978.474763  2439.540162  2847.652177  3212.852886  3547.924521  ...   

        Col119       Col120       Col121       Col122       Col123  \
0  4008.077109  3632.834002  3221.982426  2780.090228  2311.720161   
1  -850.916937  -165.252287   524.062959  1199.684611  1842.437384   
2  1161.338395   563.322919   -47.475988  -656.447463 -1252.637741   
3 -1450.758930  -722.183210    67.562203   850.005032  1561.232918   
4 -4805.126485 -4506.574476 -4196.154858 -3881.168803 -3560.705563   

        Col124       Col125       Col126       Col127       Col128  
0  1821.438861  1311.983509   790.659456   262.031836  -269.335205  
1  2437.714882  2972.733259  3437.450839  3828.215741  4143.201102  
2 -1825.089177 -2364.673580 -2861.346591 -3309.630078 -3706.785897  
3  2152.858410  2601.141643  2912.474970  3123.378574  3286.805684  
4 -3225.633496 -2860.433401 -2452.321914 -1991.255895 -1474.497200  

[5 rows x 128 columns]

In [11]:
data.shape

(11998, 128)

In [53]:
header = ["output"]
out1.columns = header
out2.columns = header

In [13]:
out2.head()

output
0       1
1       2
2       2
3       3
4       3

In [54]:
output = out1.append(out2, ignore_index = True)
output.head()

output
0       1
1       2
2       2
3       3
4       3

In [15]:
output.shape

(11998, 1)

In [55]:
data['output'] = output

In [56]:
data.head()

Col1         Col2         Col3         Col4         Col5  \
0  -797.962914 -1320.199586 -1828.741445 -2319.935857 -2789.218649   
1  4387.885674  4567.747164  4693.741356  4776.824895  4824.300958   
2 -4050.074299 -4340.408587 -4576.875995 -4769.518913 -4918.338175   
3  3458.450134  3686.700705  4000.773209  4392.451258  4834.343975   
4  -910.262100  -312.245917   298.552078   896.568469  1462.629392   

          Col6         Col7         Col8         Col9        Col10  ...  \
0 -3231.111864 -3641.962908 -4018.119193 -4355.929647 -4650.829055  ...   
1  4850.777519  4862.646175  4867.211521  4866.298624  4858.081691  ...   
2 -5025.159834 -5100.026323 -5141.111052 -5153.892968 -5137.458861  ...   
3  5269.845213  5636.871457  5876.078192  5950.944421  5841.384319  ...   
4  1978.474763  2439.540162  2847.652177  3212.852886  3547.924521  ...   

        Col120       Col121       Col122       Col123       Col124  \
0  3632.834002  3221.982426  2780.090228  2311.720161  1821.438861   
1  -165.252287   524.062959  1199.684611  1842.437384  2437.714882   
2   563.322919   -47.475988  -656.447463 -1252.637741 -1825.089177   
3  -722.183210    67.562203   850.005032  1561.232918  2152.858410   
4 -4506.574476 -4196.154858 -3881.168803 -3560.705563 -3225.633496   

        Col125       Col126       Col127       Col128  output  
0  1311.983509   790.659456   262.031836  -269.335205       1  
1  2972.733259  3437.450839  3828.215741  4143.201102       2  
2 -2364.673580 -2861.346591 -3309.630078 -3706.785897       2  
3  2601.141643  2912.474970  3123.378574  3286.805684       3  
4 -2860.433401 -2452.321914 -1991.255895 -1474.497200       3  

[5 rows x 129 columns]

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
data_arr = data.to_numpy()

In [59]:
data_arr.shape

(11998, 129)

In [60]:
x_train, x_test, y_train, y_test = train_test_split(data.loc[:,data.columns != 'output'],data['output'],test_size=0.2)

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=1)


In [61]:
print('x_train',x_train.shape)
print('y_train',y_train.shape)
print('x_val',x_val.shape)
print('y_val',y_val.shape)
print('x_test',x_test.shape)
print('y_test',y_test.shape)

x_train (7198, 128)
y_train (7198,)
x_val (2400, 128)
y_val (2400,)
x_test (2400, 128)
y_test (2400,)


In [62]:
x_train.head()

Col1         Col2         Col3         Col4         Col5  \
380    5627.591814  5545.320293  5419.464740  5201.681224  4965.830428   
1124   1110.592181   508.449757   -60.647589  -664.240326 -1238.265851   
6986   6810.227809  6499.413892  6048.095477  5532.911430  5025.177687   
10921  5835.492589  5922.700057  5970.558144  5985.447370  5966.303909   
9972   5216.278751  5229.041890  5233.950499  5232.968568  5224.132436   

              Col6         Col7         Col8         Col9        Col10  ...  \
380    4682.154155  8797.338954  4851.689220  3998.400078  3098.966748  ...   
1124  -1821.556697 -2367.740171 -2903.118990 -3425.211055 -3882.446336  ...   
6986   4584.503865  4240.692838  3990.550836  3796.824348  3602.034269  ...   
10921  5913.129135  5822.730627  5689.791149  5511.121083  5284.592885  ...   
9972   5203.515559  5163.261724  5092.572679  4981.629922  4817.670097  ...   

            Col119       Col120       Col121       Col122       Col123  \
380    3653.620775  4090.851607  4457.780632  4753.625236  5060.729835   
1124   5588.002904  5325.496652  5001.883275  4635.967165  4218.363227   
6986   3831.950756  4032.064072  4298.171428  4663.270974  5119.911906   
10921  2106.818658  2735.354399  3313.904719  3837.152909  4299.780342   
9972   2620.411472  3195.743632  3695.477544  4115.685713  4455.386809   

            Col124       Col125       Col126       Col127       Col128  
380    5292.813651  5442.125147  5593.787387  5645.113465  5668.279220  
1124   3792.417334  3290.735354  2788.640260  2262.055817  1682.069596  
6986   5635.096717  6142.829659  6570.731110  6850.675995  6937.959554  
10921  4698.597327  5036.794758  5313.308176  5536.645348  5711.061318  
9972   4718.508264  4910.939762  5046.428149  5136.752650  5187.806673  

[5 rows x 128 columns]

In [63]:
x_test.head()

Col1         Col2         Col3         Col4         Col5  \
4897  -4994.090068 -5198.078741 -5340.974175 -5436.237500 -5489.046736   
2230   1824.283087  2317.557854  2783.203056  3224.280418  3650.224652   
5991  -6524.869768 -6607.783023 -6487.457451 -6192.205426 -5763.483369   
9007  -1301.666191 -1914.821206 -2488.970680 -3051.760377 -3600.583899   
11919 -2741.917528 -3197.713952 -3604.566622 -3979.808413 -4336.695819   

              Col6         Col7         Col8         Col9        Col10  ...  \
4897  -5519.075733 -5533.571833 -5537.713592 -5536.678257 -5527.359519  ...   
2230   4028.059908  4358.137159  4666.607428  4910.953746  5125.824956  ...   
5991  -5275.104378 -4791.780010 -4373.169756 -4045.560815 -3807.942951  ...   
9007  -4081.229858 -4531.732660 -4962.817423 -5305.959513 -5640.993470  ...   
11919 -4687.466066 -5034.157169 -5371.670397 -5679.614306 -5938.612406  ...   

            Col119       Col120       Col121       Col122       Col123  \
4897    947.458737   169.817769  -611.964609 -1378.215555 -2108.224780   
2230  -3250.713865 -2810.396409 -2334.494708 -1838.271717 -1332.469146   
5991  -3243.728432 -3476.290624 -3658.295035 -3847.377663 -4100.161775   
9007   4434.346756  3986.590679  3459.223120  2931.420783  2377.874730   
11919  3176.302247  2720.505678  2205.567032  1628.429025   996.226946   

            Col124       Col125       Col126       Col127       Col128  
4897  -2782.318395 -3389.105493 -3916.161698 -4358.308776 -4716.583197  
2230   -798.820325  -284.121855   266.376788   790.818934  1319.996716  
5991  -4446.982543 -4880.760372 -5369.140220 -5851.451903 -6257.929550  
9007   1768.192680  1173.842028   538.466800   -59.675473  -700.273863  
11919   327.317425  -354.847683 -1022.737566 -1653.919807 -2229.018886  

[5 rows x 128 columns]

In [64]:
y_train.head()

380      5
1124     5
6986     3
10921    2
9972     2
Name: output, dtype: int64

In [65]:
y_test.head()

4897     2
2230     5
5991     3
9007     5
11919    3
Name: output, dtype: int64

In [66]:
y_train_hot = pd.get_dummies(y_train)
y_test_hot = pd.get_dummies(y_test)
y_val_hot = pd.get_dummies(y_val)

In [67]:
y_train_arr = y_train_hot.to_numpy()
y_test_arr = y_test_hot.to_numpy()
y_val_arr = y_val_hot.to_numpy()
print("y_train:",y_train_arr.shape)
print("y_test:",y_test_arr.shape)
print("y_val:",y_val_arr.shape)

y_train: (7198, 5)
y_test: (2400, 5)
y_val: (2400, 5)


In [102]:
y_train_hot.head()

1  2  3  4  5
380    0  0  0  0  1
1124   0  0  0  0  1
6986   0  0  1  0  0
10921  0  1  0  0  0
9972   0  1  0  0  0

In [68]:
transform = StandardScaler()
x_train_tr = transform.fit_transform(x_train)
x_test_tr = transform.fit_transform(x_test)
x_val_tr = transform.fit_transform(x_val)

In [69]:
print("Training",x_train_tr.shape)
print(y_train_arr.shape)
print("Validation",x_val_tr.shape)
print(y_val_arr.shape)
print("Test",x_test_tr.shape)
print(y_test_arr.shape)

Training (7198, 128)
(7198, 5)
Validation (2400, 128)
(2400, 5)
Test (2400, 128)
(2400, 5)


In [70]:
model = Sequential()

model.add(Dense(128, input_shape=(128,), activation = 'relu'))

model.add(Dense(256, activation = 'relu'))
model.add(Dropout(0.6))

model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.5))

model.add(Dense(5, activation = 'softmax'))

model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')


In [84]:
history = model.fit(x_train_tr, y_train_arr, batch_size=64, epochs=30, validation_data=(x_val_tr, y_val_arr))


Epoch 1/30
113/113 [==============================] - 0s 3ms/step - loss: 5.8892e-04 - accuracy: 0.9997 - val_loss: 3.8455e-06 - val_accuracy: 1.0000
Epoch 2/30
113/113 [==============================] - 0s 3ms/step - loss: 3.0182e-04 - accuracy: 1.0000 - val_loss: 1.6767e-06 - val_accuracy: 1.0000
Epoch 3/30
113/113 [==============================] - 0s 2ms/step - loss: 4.5962e-04 - accuracy: 1.0000 - val_loss: 2.4155e-06 - val_accuracy: 1.0000
Epoch 4/30
113/113 [==============================] - 0s 3ms/step - loss: 7.5125e-04 - accuracy: 0.9999 - val_loss: 1.5215e-05 - val_accuracy: 1.0000
Epoch 5/30
113/113 [==============================] - 0s 2ms/step - loss: 4.5035e-04 - accuracy: 1.0000 - val_loss: 2.4153e-05 - val_accuracy: 1.0000
Epoch 6/30
113/113 [==============================] - 0s 2ms/step - loss: 0.2033 - accuracy: 0.9404 - val_loss: 0.0141 - val_accuracy: 0.9979
Epoch 7/30
113/113 [==============================] - 0s 3ms/step - loss: 0.0411 - accuracy: 0.9879 - val_lo

In [78]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_5 (Dense)              (None, 256)               33024     
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 128)               32896     
_________________________________________________________________
dropout_3 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 5)                 645       
Total params: 83,077
Trainable params: 83,077
Non-trainable params: 0
__________________________________________________

In [85]:
pred_acc = model.evaluate(x_test_tr,y_test_arr)
print("Test accuracy is {}".format(pred_acc))

75/75 [==============================] - 0s 1ms/step - loss: 2.4163e-05 - accuracy: 1.0000
Test accuracy is [2.4163484340533614e-05, 1.0]


In [101]:
d = x_test.to_numpy()
for i in range(0,5):
    print((model.predict(d))[i])

[0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0.]


In [98]:
x_test.head()

Col1         Col2         Col3         Col4         Col5  \
4897  -4994.090068 -5198.078741 -5340.974175 -5436.237500 -5489.046736   
2230   1824.283087  2317.557854  2783.203056  3224.280418  3650.224652   
5991  -6524.869768 -6607.783023 -6487.457451 -6192.205426 -5763.483369   
9007  -1301.666191 -1914.821206 -2488.970680 -3051.760377 -3600.583899   
11919 -2741.917528 -3197.713952 -3604.566622 -3979.808413 -4336.695819   

              Col6         Col7         Col8         Col9        Col10  ...  \
4897  -5519.075733 -5533.571833 -5537.713592 -5536.678257 -5527.359519  ...   
2230   4028.059908  4358.137159  4666.607428  4910.953746  5125.824956  ...   
5991  -5275.104378 -4791.780010 -4373.169756 -4045.560815 -3807.942951  ...   
9007  -4081.229858 -4531.732660 -4962.817423 -5305.959513 -5640.993470  ...   
11919 -4687.466066 -5034.157169 -5371.670397 -5679.614306 -5938.612406  ...   

            Col119       Col120       Col121       Col122       Col123  \
4897    947.458737   169.817769  -611.964609 -1378.215555 -2108.224780   
2230  -3250.713865 -2810.396409 -2334.494708 -1838.271717 -1332.469146   
5991  -3243.728432 -3476.290624 -3658.295035 -3847.377663 -4100.161775   
9007   4434.346756  3986.590679  3459.223120  2931.420783  2377.874730   
11919  3176.302247  2720.505678  2205.567032  1628.429025   996.226946   

            Col124       Col125       Col126       Col127       Col128  
4897  -2782.318395 -3389.105493 -3916.161698 -4358.308776 -4716.583197  
2230   -798.820325  -284.121855   266.376788   790.818934  1319.996716  
5991  -4446.982543 -4880.760372 -5369.140220 -5851.451903 -6257.929550  
9007   1768.192680  1173.842028   538.466800   -59.675473  -700.273863  
11919   327.317425  -354.847683 -1022.737566 -1653.919807 -2229.018886  

[5 rows x 128 columns]

In [99]:
y_test.head()

4897     2
2230     5
5991     3
9007     5
11919    3
Name: output, dtype: int64