In [185]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.optimizers import Adam

In [186]:
data1 = pd.read_csv("Dataset/Train/Voltage_L1_DataSet1.csv")
out1 = pd.read_csv("Dataset/Train/OutputFor_DataSet1.csv")
data2 = pd.read_csv("Dataset/Test/Voltage_L1_DataSet2.csv")
out2 = pd.read_csv("Dataset/Test/OutputFor_DataSet2.csv")

In [187]:
print("data1",data1.shape)
print("out1",out1.shape)
print("data2",data2.shape)
print("out2",out2.shape)

data1 (11899, 128)
out1 (5999, 1)
data2 (5999, 128)
out2 (5999, 1)


In [188]:
data1.dropna(axis=0,inplace=True)

In [189]:
data1.shape

(5999, 128)

In [190]:
header =[]
for i in range(1,data1.shape[1]+1):
    header.append("Col"+str(i))

In [191]:
data1.columns = header
data2.columns = header

In [192]:
data1.head()

Col1         Col2         Col3         Col4         Col5  \
0  -797.962914 -1320.199586 -1828.741445 -2319.935857 -2789.218649   
1  4387.885674  4567.747164  4693.741356  4776.824895  4824.300958   
2 -4050.074299 -4340.408587 -4576.875995 -4769.518913 -4918.338175   
3  3458.450134  3686.700705  4000.773209  4392.451258  4834.343975   
4  -910.262100  -312.245917   298.552078   896.568469  1462.629392   

          Col6         Col7         Col8         Col9        Col10  ...  \
0 -3231.111864 -3641.962908 -4018.119193 -4355.929647 -4650.829055  ...   
1  4850.777519  4862.646175  4867.211521  4866.298624  4858.081691  ...   
2 -5025.159834 -5100.026323 -5141.111052 -5153.892968 -5137.458861  ...   
3  5269.845213  5636.871457  5876.078192  5950.944421  5841.384319  ...   
4  1978.474763  2439.540162  2847.652177  3212.852886  3547.924521  ...   

        Col119       Col120       Col121       Col122       Col123  \
0  4008.077109  3632.834002  3221.982426  2780.090228  2311.720161   
1  -850.916937  -165.252287   524.062959  1199.684611  1842.437384   
2  1161.338395   563.322919   -47.475988  -656.447463 -1252.637741   
3 -1450.758930  -722.183210    67.562203   850.005032  1561.232918   
4 -4805.126485 -4506.574476 -4196.154858 -3881.168803 -3560.705563   

        Col124       Col125       Col126       Col127       Col128  
0  1821.438861  1311.983509   790.659456   262.031836  -269.335205  
1  2437.714882  2972.733259  3437.450839  3828.215741  4143.201102  
2 -1825.089177 -2364.673580 -2861.346591 -3309.630078 -3706.785897  
3  2152.858410  2601.141643  2912.474970  3123.378574  3286.805684  
4 -3225.633496 -2860.433401 -2452.321914 -1991.255895 -1474.497200  

[5 rows x 128 columns]

In [193]:
data2.head()

Col1         Col2         Col3         Col4         Col5  \
0 -4918.927835 -4668.999112 -4375.127119 -4034.564431 -3659.213495   
1  2920.413836  2376.612648  1773.304349  1123.306756   444.013104   
2 -2808.723170 -2303.372710 -1758.656432 -1180.066319  -579.504820   
3  2871.892861  2532.245964  2055.275298  1435.488878   704.927781   
4  5534.138053  5395.898976  5186.251418  4924.421624  4631.464792   

          Col6         Col7         Col8         Col9        Col10  ...  \
0 -3247.243211 -2804.145676 -2333.584172 -1841.965323 -1332.037736  ...   
1  -248.097664  -933.799415 -1594.783666 -2213.654301 -2776.681104  ...   
2    32.957795   643.590017  1241.404644  1815.417600  2356.471851  ...   
3   -86.971408  -871.546088 -1584.713275 -2177.034698 -2625.625239  ...   
4  4323.859863  4009.847091  3692.171624  3363.511349  3012.878248  ...   

        Col119       Col120       Col121       Col122       Col123  \
0 -4663.506099 -4918.012016 -5121.251501 -5275.969344 -5381.249941   
1  4871.323226  4852.098262  4814.562485  4748.647181  4645.197563   
2 -5151.462319 -5106.602976 -5027.871511 -4914.350757 -4759.632168   
3  5858.221546  5590.898767  5202.730284  4759.633062  4322.945050   
4  3558.510431  3879.847783  4193.860201  4506.042306  4808.154800   

        Col124       Col125       Col126       Col127       Col128  
0 -5433.432863 -5434.348878 -5382.165656 -5278.715575 -5123.997634  
1  4492.310731  4274.423564  3991.537412  3633.580485  3201.469277  
2 -4565.548254 -4319.281944 -4020.831887 -3671.114971 -3265.552744  
3  3943.932165  3647.312850  3432.172965  3265.553468  3098.018896  
4  5085.548312  5318.082271  5487.448225  5576.250464  5574.419599  

[5 rows x 128 columns]

In [194]:
data = data1.append(data2, ignore_index = True)
data.head()

Col1         Col2         Col3         Col4         Col5  \
0  -797.962914 -1320.199586 -1828.741445 -2319.935857 -2789.218649   
1  4387.885674  4567.747164  4693.741356  4776.824895  4824.300958   
2 -4050.074299 -4340.408587 -4576.875995 -4769.518913 -4918.338175   
3  3458.450134  3686.700705  4000.773209  4392.451258  4834.343975   
4  -910.262100  -312.245917   298.552078   896.568469  1462.629392   

          Col6         Col7         Col8         Col9        Col10  ...  \
0 -3231.111864 -3641.962908 -4018.119193 -4355.929647 -4650.829055  ...   
1  4850.777519  4862.646175  4867.211521  4866.298624  4858.081691  ...   
2 -5025.159834 -5100.026323 -5141.111052 -5153.892968 -5137.458861  ...   
3  5269.845213  5636.871457  5876.078192  5950.944421  5841.384319  ...   
4  1978.474763  2439.540162  2847.652177  3212.852886  3547.924521  ...   

        Col119       Col120       Col121       Col122       Col123  \
0  4008.077109  3632.834002  3221.982426  2780.090228  2311.720161   
1  -850.916937  -165.252287   524.062959  1199.684611  1842.437384   
2  1161.338395   563.322919   -47.475988  -656.447463 -1252.637741   
3 -1450.758930  -722.183210    67.562203   850.005032  1561.232918   
4 -4805.126485 -4506.574476 -4196.154858 -3881.168803 -3560.705563   

        Col124       Col125       Col126       Col127       Col128  
0  1821.438861  1311.983509   790.659456   262.031836  -269.335205  
1  2437.714882  2972.733259  3437.450839  3828.215741  4143.201102  
2 -1825.089177 -2364.673580 -2861.346591 -3309.630078 -3706.785897  
3  2152.858410  2601.141643  2912.474970  3123.378574  3286.805684  
4 -3225.633496 -2860.433401 -2452.321914 -1991.255895 -1474.497200  

[5 rows x 128 columns]

In [195]:
data.shape

(11998, 128)

In [196]:
header = ["output"]
out1.columns = header
out2.columns = header

In [197]:
out2.head()

output
0       1
1       2
2       2
3       3
4       3

In [198]:
output = out1.append(out2, ignore_index = True)
output.head()

output
0       1
1       2
2       2
3       3
4       3

In [199]:
output.shape

(11998, 1)

In [200]:
data['output'] = output

In [201]:
data.head()

Col1         Col2         Col3         Col4         Col5  \
0  -797.962914 -1320.199586 -1828.741445 -2319.935857 -2789.218649   
1  4387.885674  4567.747164  4693.741356  4776.824895  4824.300958   
2 -4050.074299 -4340.408587 -4576.875995 -4769.518913 -4918.338175   
3  3458.450134  3686.700705  4000.773209  4392.451258  4834.343975   
4  -910.262100  -312.245917   298.552078   896.568469  1462.629392   

          Col6         Col7         Col8         Col9        Col10  ...  \
0 -3231.111864 -3641.962908 -4018.119193 -4355.929647 -4650.829055  ...   
1  4850.777519  4862.646175  4867.211521  4866.298624  4858.081691  ...   
2 -5025.159834 -5100.026323 -5141.111052 -5153.892968 -5137.458861  ...   
3  5269.845213  5636.871457  5876.078192  5950.944421  5841.384319  ...   
4  1978.474763  2439.540162  2847.652177  3212.852886  3547.924521  ...   

        Col120       Col121       Col122       Col123       Col124  \
0  3632.834002  3221.982426  2780.090228  2311.720161  1821.438861   
1  -165.252287   524.062959  1199.684611  1842.437384  2437.714882   
2   563.322919   -47.475988  -656.447463 -1252.637741 -1825.089177   
3  -722.183210    67.562203   850.005032  1561.232918  2152.858410   
4 -4506.574476 -4196.154858 -3881.168803 -3560.705563 -3225.633496   

        Col125       Col126       Col127       Col128  output  
0  1311.983509   790.659456   262.031836  -269.335205       1  
1  2972.733259  3437.450839  3828.215741  4143.201102       2  
2 -2364.673580 -2861.346591 -3309.630078 -3706.785897       2  
3  2601.141643  2912.474970  3123.378574  3286.805684       3  
4 -2860.433401 -2452.321914 -1991.255895 -1474.497200       3  

[5 rows x 129 columns]

In [202]:
from sklearn.model_selection import train_test_split

In [203]:
data_arr = data.to_numpy()

In [204]:
data_arr.shape

(11998, 129)

In [205]:
x_train, x_test, y_train, y_test = train_test_split(data.loc[:,data.columns != 'output'],data['output'],test_size=0.2)

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.25, random_state=42)


In [206]:
print('x_train',x_train.shape)
print('y_train',y_train.shape)
print('x_val',x_val.shape)
print('y_val',y_val.shape)
print('x_test',x_test.shape)
print('y_test',y_test.shape)

x_train (7198, 128)
y_train (7198,)
x_val (2400, 128)
y_val (2400,)
x_test (2400, 128)
y_test (2400,)


In [207]:
x_train.head()

Col1         Col2         Col3         Col4         Col5  \
8828   3470.385506  3019.880482  2543.819352  2038.184147  1517.028851   
2875   4721.208744  5063.989520  5369.902016  5571.186379  5712.682588   
875   -1151.290625 -1774.174349 -2380.579154 -2965.013227 -3519.785560   
10360   722.950321   -56.109485  -833.010389 -1565.671515 -2221.721647   
6735   -954.451171  -326.144166   315.593046   944.859058  1538.633751   

              Col6         Col7         Col8         Col9        Col10  ...  \
8828    979.076154   436.301852  -118.483428  -671.105206 -1210.468446  ...   
2875   5773.466306  5806.349424  5840.229426  5820.299529  5755.530422  ...   
875   -4041.601818 -4524.968316 -4963.293306 -5353.282346 -5693.835652  ...   
10360 -2784.975504 -3255.432997 -3650.357085 -3996.726648 -4327.988645  ...   
6735   2080.608692  2565.028992  2992.853254  3376.552701  3728.595978  ...   

            Col119       Col120       Col121       Col122       Col123  \
8828   5601.349319  5612.801233  5575.042933  5478.116689  5335.771243   
2875     -1.992104   245.128690   852.966486  1404.007347  1981.951206   
875    4691.950458  4228.358140  3721.922199  3181.430799  2609.080079   
10360  5362.779225  4974.328259  4608.537247  4269.721702  3937.380681   
6735  -5050.438804 -4734.846055 -4409.660657 -4078.720840 -3742.025081   

            Col124       Col125       Col126       Col127       Col128  
8828   5139.622415  4892.051064  4599.656769  4261.692735  3882.444225  
2875   2495.126676  3024.244569  3552.365758  3951.945306  4384.406747  
875    2011.463896  1392.974160   763.499730   125.236405  -514.126009  
10360  3585.616738  3182.059113  2700.812016  2125.689624  1457.769537  
6735  -3389.980406 -3006.281672 -2577.497672 -2093.078165 -1550.143939  

[5 rows x 128 columns]

In [208]:
x_test.head()

Col1         Col2         Col3         Col4         Col5  \
3952  -5127.342110 -5361.155835 -5532.374235 -5621.665696 -5621.665434   
11351 -4313.177310 -4757.467545 -5157.436285 -5506.598569 -5807.115363   
1258  -2809.857638 -3254.717114 -3685.407673 -4071.817707 -4418.938186   
6351  -1999.138860 -2460.268444 -2869.245494 -3234.305659 -3571.002357   
280   -3109.873666 -2666.315218 -2166.194791 -1604.551928  -989.324777   

              Col6         Col7         Col8         Col9        Col10  ...  \
3952  -5531.453477 -5360.236183 -5125.500623 -4846.580644 -4544.647151  ...   
11351 -6047.096777 -6229.785150 -6354.099834 -6415.716438 -6416.797400  ...   
1258  -4718.196496 -4967.154785 -3198.391129 -4942.339319 -5244.693565  ...   
6351  -3891.231638 -4205.969489 -4517.963307 -4819.893218 -5097.119958  ...   
280    -339.366645   324.482809   974.440821  1589.668628  2150.318312  ...   

            Col119       Col120       Col121       Col122       Col123  \
3952  -1493.096025 -2012.274061 -2477.141108 -2887.696876 -3255.908059   
11351  1552.312208   935.063143   308.084146  -321.055393  -948.033582   
1258   2395.669623  1890.760374  1367.746283   836.569222   299.692729   
6351   3216.922738  2850.947842  2441.970444  1979.927004  1462.071903   
280   -6059.986884 -5961.749363 -5777.181117 -5524.143939 -5222.484369   

            Col124       Col125       Col126       Col127       Col128  
3952  -3593.742346 -3915.927250 -4232.588670 -4546.488743 -4850.262543  
11351 -1565.283122 -2167.398416 -2748.975169 -3304.607159 -3827.810017  
1258   3590.306235    -8.730831  -927.203028 -1834.937705 -2332.991012  
6351    895.725018   295.525819  -315.653529  -914.937168 -1481.284516  
280   -4898.001331 -4560.619627 -4218.274630 -3869.977037 -3505.802486  

[5 rows x 128 columns]

In [209]:
y_train.head()

8828     5
2875     4
875      1
10360    3
6735     3
Name: output, dtype: int64

In [210]:
y_test.head()

3952     3
11351    1
1258     5
6351     3
280      3
Name: output, dtype: int64

In [211]:
y_train_hot = pd.get_dummies(y_train)
y_test_hot = pd.get_dummies(y_test)
y_val_hot = pd.get_dummies(y_val)

In [212]:
y_train_arr = y_train_hot.to_numpy()
y_test_arr = y_test_hot.to_numpy()
y_val_arr = y_val_hot.to_numpy()
print("y_train:",y_train_arr.shape)
print("y_test:",y_test_arr.shape)
print("y_val:",y_val_arr.shape)

y_train: (7198, 5)
y_test: (2400, 5)
y_val: (2400, 5)


In [213]:
y_train_hot.head()

1  2  3  4  5
8828   0  0  0  0  1
2875   0  0  0  1  0
875    1  0  0  0  0
10360  0  0  1  0  0
6735   0  0  1  0  0

In [214]:
transform = StandardScaler()
x_train_tr = transform.fit_transform(x_train)
x_test_tr = transform.fit_transform(x_test)
x_val_tr = transform.fit_transform(x_val)

In [215]:
print("Training",x_train_tr.shape)
print(y_train_arr.shape)
print("Validation",x_val_tr.shape)
print(y_val_arr.shape)
print("Test",x_test_tr.shape)
print(y_test_arr.shape)

Training (7198, 128)
(7198, 5)
Validation (2400, 128)
(2400, 5)
Test (2400, 128)
(2400, 5)


In [222]:
model = Sequential()

model.add(Dense(128, input_shape=(128,), activation = 'relu'))

model.add(Dense(64, activation = 'relu'))
#model.add(Dense(64, activation = 'relu'))
#model.add(Dropout(0.6))

model.add(Dense(32, activation = 'relu'))
#model.add(Dropout(0.6))

model.add(Dense(32, activation = 'relu'))
#model.add(Dropout(0.5))

model.add(Dense(5, activation = 'softmax'))

model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')


In [223]:
history = model.fit(x_train_tr, y_train_arr, batch_size=64, epochs=30, validation_data=(x_val_tr, y_val_arr))


Epoch 1/30
113/113 [==============================] - 1s 6ms/step - loss: 1.2922 - accuracy: 0.4005 - val_loss: 1.1435 - val_accuracy: 0.4400
Epoch 2/30
113/113 [==============================] - 1s 6ms/step - loss: 1.1223 - accuracy: 0.4654 - val_loss: 1.1114 - val_accuracy: 0.4767
Epoch 3/30
113/113 [==============================] - 1s 6ms/step - loss: 1.0815 - accuracy: 0.4990 - val_loss: 1.0905 - val_accuracy: 0.5121
Epoch 4/30
113/113 [==============================] - 1s 6ms/step - loss: 0.9055 - accuracy: 0.5971 - val_loss: 0.7921 - val_accuracy: 0.6392
Epoch 5/30
113/113 [==============================] - 1s 6ms/step - loss: 0.7052 - accuracy: 0.6663 - val_loss: 0.6704 - val_accuracy: 0.7042
Epoch 6/30
113/113 [==============================] - 1s 7ms/step - loss: 0.6919 - accuracy: 0.6749 - val_loss: 0.6151 - val_accuracy: 0.6871
Epoch 7/30
113/113 [==============================] - 1s 8ms/step - loss: 0.6409 - accuracy: 0.6930 - val_loss: 0.6325 - val_accuracy: 0.6875
Epoch 

In [224]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_36 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_37 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_38 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_39 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_40 (Dense)             (None, 5)                 165       
Total params: 28,069
Trainable params: 28,069
Non-trainable params: 0
_________________________________________________________________


In [225]:
print(model.metrics_names)

['loss', 'accuracy']


In [226]:
pred_acc = model.evaluate(x_test_tr,y_test_arr)
print("Test accuracy is {}".format(pred_acc))

75/75 [==============================] - 0s 4ms/step - loss: 0.0049 - accuracy: 1.0000
Test accuracy is [0.004882120061665773, 1.0]


In [221]:
d = x_test.to_numpy()
for i in range(0,5):
    print((model.predict(d))[i])

[0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
