In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy.fft import fft,fftfreq
from sklearn.preprocessing import StandardScaler

In [2]:
x_train = pd.read_csv("Dataset2/Train/Voltage_L1_train.csv")
x_test = pd.read_csv("Dataset2/Test/Voltage_L1_test.csv")
y_train = pd.read_csv("Dataset2/Train/output_train.csv")
y_test = pd.read_csv("Dataset2/Test/output_test.csv")

In [3]:
header =[]
for i in range(1,x_train.shape[1]+1):
    header.append("Col"+str(i))
x_train.columns = header
x_test.columns = header

In [4]:
x_train.head()

Col1         Col2         Col3         Col4         Col5  \
0   573.652486  1003.343736  1588.404525  2317.576741  2804.364311   
1  4757.365183  5264.598912  5428.642486  5650.413073  5939.710012   
2  4242.144824  4644.679402  5013.356532  5229.417051  5534.898007   
3  2077.819247  2561.679246  3085.653813  3545.905160  4023.421592   
4  3599.645319  4099.944762  4499.282469  4897.875855  5120.077118   

          Col6         Col7         Col8         Col9        Col10  ...  \
0  3225.322510  3662.821690  4174.627969  4656.244143  4939.070130  ...   
1  5911.948067  6147.642171  6076.921501  5958.797444  6053.817701  ...   
2  5797.190678  5930.658682  5960.014599  6055.336310  6103.707793  ...   
3  4496.705157  4809.079868  5186.298840  5453.627533  5737.354699  ...   
4  5402.227743  5694.801362  5928.683099  5981.616502  6052.006904  ...   

        Col247       Col248       Col249       Col250       Col251  \
0 -4650.282434 -4228.581226 -3865.609932 -3395.654756 -2933.680470   
1  -280.360872   323.325836   861.103019  1415.929276  2007.692919   
2 -1256.270585  -616.527428   -67.068193   549.016676  1099.652199   
3 -3557.345152 -3017.951179 -2596.647329 -1996.266675 -1467.203661   
4 -2020.240712 -1388.704968  -849.731284  -232.632694   341.406093   

        Col252       Col253       Col254       Col255       Col256  
0 -2322.450904 -1841.562453 -1282.042025  -601.968217  -156.848367  
1  2561.130303  2960.282598  3619.932691  4008.288701  4422.229911  
2  1697.572166  2239.961604  2776.876479  3248.638662  3807.665149  
3  -885.101101  -329.685256   304.222722   935.528504  1460.127297  
4   854.579135  1528.023058  2002.557438  2576.468343  3036.303600  

[5 rows x 256 columns]

In [5]:
x_test.head()

Col1         Col2         Col3         Col4         Col5  \
0  4216.164293  4550.919227  4885.253969  5265.577080  5634.058181   
1   795.638794  1340.736614  1928.805243  2465.916079  3009.942949   
2  1220.943267  1770.550513  2318.816674  2850.186275  3357.786987   
3  1013.772210  1621.783618  2178.146635  2733.460484  3178.151416   
4  4490.355896  4862.601717  5235.681699  5401.432840  5741.255908   

          Col6         Col7         Col8         Col9        Col10  ...  \
0  5690.878844  5984.805444  6083.124480  6024.018340  6144.339029  ...   
1  3475.153730  3938.568022  4372.781654  4765.603003  5090.817748  ...   
2  3848.017230  4274.339651  4669.175893  5027.840955  5329.856655  ...   
3  3692.797702  4177.895304  4539.640464  4948.873847  5271.862849  ...   
4  5840.507807  6030.352157  6037.480783  6109.355580  6000.190091  ...   

        Col247       Col248       Col249       Col250       Col251  \
0 -1279.720481  -672.204610   -35.247405   565.001817  1139.580709   
1 -4525.083123 -4077.498908 -3630.262875 -3176.648183 -2652.563485   
2 -4214.790563 -3762.024055 -3303.182589 -2802.950592 -2246.516780   
3 -4371.401183 -3937.075334 -3502.317297 -2922.179500 -2467.320667   
4  -848.410798  -279.507713   269.777288   853.806015  1410.187144   

        Col252       Col253       Col254       Col255       Col256  
0  1623.258946  2159.189259  2729.066018  3292.437301  3770.985050  
1 -2135.982927 -1549.968773  -970.063115  -413.973048   202.507328  
2 -1712.153266 -1120.729328  -553.276475    43.863168   614.870963  
3 -1904.033355 -1362.385474  -704.032900  -188.518269   466.064827  
4  1977.999116  2621.735468  3069.781180  3624.993700  4116.325633  

[5 rows x 256 columns]

In [6]:
y_train.tail()

1
5994  6
5995  6
5996  6
5997  6
5998  6

In [7]:
y_test.head()

1
0  1
1  1
2  1
3  1
4  1

In [8]:
header = ["output"]
y_train.columns = header
y_test.columns = header
y_train_hot = pd.get_dummies(y_train['output'])
y_test_hot = pd.get_dummies(y_test['output'])
y_train = y_train.to_numpy()
y_test= y_test.to_numpy()
y_train = y_train.flatten()
y_test = y_test.flatten()

In [9]:
print("x_train",x_train.shape)
print("y_train",y_train.shape)
print("x_test",x_test.shape)
print("y_test",y_test.shape)

x_train (5999, 256)
y_train (5999,)
x_test (3599, 256)
y_test (3599,)


In [10]:
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

In [11]:
for i in range(0,x_train.shape[0]):
    x_train[i][:] = np.abs(fft(x_train[i][:]))
    
for i in range(0,x_test.shape[0]):
    x_test[i][:] = np.abs(fft(x_test[i][:]))

In [12]:
transform = StandardScaler()
x_train = transform.fit_transform(x_train)
x_test = transform.fit_transform(x_test)

In [13]:
from sklearn.ensemble import RandomForestClassifier

modelR = RandomForestClassifier(24) 



# fit the model

modelR.fit(x_train,y_train_hot)

RandomForestClassifier(n_estimators=24)

In [14]:
predict_testR=modelR.predict(x_test)
predict_testR

array([[1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1]], dtype=uint8)

In [15]:
from sklearn.metrics import accuracy_score

accuracy_test=accuracy_score(y_test_hot,predict_testR)
accuracy_test

0.9944429008057794

In [16]:
from sklearn.naive_bayes import GaussianNB 

modelN = GaussianNB() 

modelN.fit(x_train, y_train) 

GaussianNB()

In [17]:
predict_testN=modelN.predict(x_test)
predict_testN

array([1, 1, 1, ..., 6, 6, 6])

In [18]:
accuracy_test=accuracy_score(y_test,predict_testN)
accuracy_test

0.9969435954431787

In [19]:
from sklearn.svm import SVC 

modelS = SVC()  
modelS.fit(x_train, y_train)  

SVC()

In [20]:
predict_testS=modelS.predict(x_test)
predict_testS

array([1, 1, 1, ..., 6, 6, 6])

In [21]:
from sklearn.metrics import accuracy_score

accuracy_test=accuracy_score(y_test,predict_testS)
accuracy_test

0.9980550152820228